remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

title: "Mikołaj Żurek"
description: "Data Engineering, Spark, Databricks, Azure"

author:
  name: "Mikołaj Żurek"

minimal_mistakes_skin: "default" # try: dark, air, contrast

paginate: 5
paginate_path: /page:num/

markdown: kramdown

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

archive:
  type: liquid

header_pages:
  - about.md
  - categories.md
  - tags.md

show_date: true
show_tags: true
show_categories: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      read_time: true
      share: false
      related: true

minimal_mistakes_skin: default

atom_feed:
  hide: false

breadcrumbs: true
